/**
 * Nombres de fuente tal como suelen aparecer en Word (Windows).
 * Solo son cadenas en el bundle (~2–3 KiB); no se incrustan archivos .ttf.
 */
const RAW_PAGE_FONT_NAMES: string[] = [
  'Agency FB',
  'Algerian',
  'Arial',
  'Arial Black',
  'Arial Narrow',
  'Bahnschrift',
  'Baskerville Old Face',
  'Bell MT',
  'Book Antiqua',
  'Bookman Old Style',
  'Braggadocio',
  'Britannic Bold',
  'Calibri',
  'Calisto MT',
  'Cambria',
  'Cambria Math',
  'Candara',
  'Castellar',
  'Century',
  'Century Gothic',
  'Century Schoolbook',
  'Colonna MT',
  'Comic Sans MS',
  'Consolas',
  'Constantia',
  'Cooper Black',
  'Corbel',
  'Courier New',
  'Ebrima',
  'Engravers MT',
  'Footlight MT Light',
  'Franklin Gothic Book',
  'Franklin Gothic Medium',
  'Gabriola',
  'Gadugi',
  'Garamond',
  'Georgia',
  'Gill Sans MT',
  'Gloucester MT Extra Condensed',
  'Goudy Old Style',
  'Haettenschweiler',
  'Harlow Solid Italic',
  'Harrington',
  'High Tower Text',
  'Impact',
  'Imprint MT Shadow',
  'Jokerman',
  'Juice ITC',
  'Kristen ITC',
  'Kunstler Script',
  'Lucida Bright',
  'Lucida Calligraphy',
  'Lucida Console',
  'Lucida Fax',
  'Lucida Handwriting',
  'Lucida Sans',
  'Lucida Sans Typewriter',
  'Lucida Sans Unicode',
  'Magneto',
  'Maiandra GD',
  'Malgun Gothic',
  'Microsoft Sans Serif',
  'Microsoft YaHei',
  'Mistral',
  'Modern No. 20',
  'Monotype Corsiva',
  'MS Gothic',
  'MS Reference Sans Serif',
  'MS Reference Specialty',
  'MT Extra',
  'MV Boli',
  'News Gothic MT',
  'Niagara Engraved',
  'Niagara Solid',
  'Onyx',
  'Palace Script MT',
  'Palatino Linotype',
  'Papyrus',
  'Parchment',
  'Perpetua',
  'Perpetua Titling MT',
  'Playbill',
  'Poor Richard',
  'Pristina',
  'Rage Italic',
  'Ravie',
  'Rockwell',
  'Rockwell Condensed',
  'Rockwell Extra Bold',
  'Segoe Print',
  'Segoe Script',
  'Segoe UI',
  'Segoe UI Historic',
  'Segoe UI Symbol',
  'Showcard Gothic',
  'SimSun',
  'Snap ITC',
  'Stencil',
  'Sylfaen',
  'Tahoma',
  'Times New Roman',
  'Trebuchet MS',
  'Tw Cen MT',
  'Tw Cen MT Condensed',
  'Tw Cen MT Condensed Extra Bold',
  'Verdana',
  'Viner Hand ITC',
  'Vivaldi',
  'Vladimir Script',
  'Wide Latin',
  'Yu Gothic',
];

export const PAGE_FONT_CHOICES: string[] = [...new Set(RAW_PAGE_FONT_NAMES)].sort((a, b) =>
  a.localeCompare(b, 'es', { sensitivity: 'base' }),
);
