import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '../..');
const migrationPath = join(root, 'supabase/migrations/20260530140000_sierju_catalog_phase_s1.sql');
const full = readFileSync(migrationPath, 'utf8');
const marker = '-- ---------------------------------------------------------------------------\n-- Seed catalogo';
const ddlEnd = full.indexOf(marker);
const ddl = ddlEnd > 0 ? full.slice(0, ddlEnd) : full.split('-- Auto-generated by scripts/sierju')[0]!;
const seedHeader =
  '-- ---------------------------------------------------------------------------\n-- Seed catalogo (regenerar: npx tsx scripts/sierju/generate-sierju-seed-sql.mts)\n-- ---------------------------------------------------------------------------\n\n';
const seed = readFileSync(join(root, 'supabase/seed/sierju_catalog_seed.sql'), 'utf8');
const footer = readFileSync(join(root, 'supabase/migrations/_sierju_s1_footer.sql'), 'utf8');
writeFileSync(migrationPath, ddl.trimEnd() + '\n' + seedHeader + seed + '\n' + footer, 'utf8');
console.error('Rebuilt migration:', migrationPath);
