/**
 * Genera SQL de seed SIERJU desde catalog-seed-data.json
 * Uso:
 *   npx tsx scripts/sierju/generate-sierju-seed-sql.mts
 *   npx tsx scripts/sierju/assemble-sierju-migration.mts
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '../..');
const data = JSON.parse(
  readFileSync(join(root, 'scripts/sierju/catalog-seed-data.json'), 'utf8'),
) as {
  formTemplates: Array<{
    code: string;
    label: string;
    version: string;
    effective_from: string;
    source_document: string;
  }>;
  sections: Array<{
    form: string;
    code: string;
    label: string;
    specialty: string;
    instance_level: number | null;
    procedure_mode: string | null;
    unit_of_measure: string;
    sort_order: number;
  }>;
  classesBySection: Record<string, [string, string][]>;
  restitucionConcurrentClasses: Record<string, [string, string][]>;
};

function esc(s: string): string {
  return s.replace(/'/g, "''");
}

const lines: string[] = [];
lines.push('-- Auto-generated by scripts/sierju/generate-sierju-seed-sql.mts');
lines.push('-- Do not edit manually; regenerate from catalog-seed-data.json');
lines.push('');

for (const t of data.formTemplates) {
  lines.push(
    `insert into public.sierju_form_templates (code, label, version, effective_from, source_document)`,
  );
  lines.push(
    `values ('${esc(t.code)}', '${esc(t.label)}', '${esc(t.version)}', '${t.effective_from}', '${esc(t.source_document)}')`,
  );
  lines.push(
    `on conflict (code) do update set label = excluded.label, version = excluded.version, effective_from = excluded.effective_from, source_document = excluded.source_document;`,
  );
  lines.push('');
}

for (const s of data.sections) {
  const inst = s.instance_level === null ? 'null' : String(s.instance_level);
  const mode = s.procedure_mode === null ? 'null' : `'${esc(s.procedure_mode)}'`;
  lines.push(`insert into public.sierju_sections (`);
  lines.push(
    `  form_template_code, code, label, specialty, instance_level, procedure_mode, unit_of_measure, sort_order`,
  );
  lines.push(`) values (`);
  lines.push(
    `  '${esc(s.form)}', '${esc(s.code)}', '${esc(s.label)}', '${esc(s.specialty)}', ${inst}, ${mode}, '${esc(s.unit_of_measure)}', ${s.sort_order}`,
  );
  lines.push(`)`);
  lines.push(
    `on conflict (form_template_code, code) do update set label = excluded.label, specialty = excluded.specialty, instance_level = excluded.instance_level, procedure_mode = excluded.procedure_mode, unit_of_measure = excluded.unit_of_measure, sort_order = excluded.sort_order;`,
  );
  lines.push('');
}

function seedClasses(form: string, sectionCode: string, classes: [string, string][]) {
  if (!classes?.length) return;
  const json = JSON.stringify(
    classes.map(([code, label], i) => ({ code, label, order: i + 1 })),
  );
  lines.push(
    `select public._sierju_seed_section_classes('${esc(form)}', '${esc(sectionCode)}', '${esc(json)}'::jsonb);`,
  );
}

for (const [sectionCode, classes] of Object.entries(data.classesBySection)) {
  const section = data.sections.find((s) => s.code === sectionCode);
  const form = section?.form ?? 'sierju_civil_circuito_2023_v4';
  seedClasses(form, sectionCode, classes);
}

for (const [sectionCode, classes] of Object.entries(data.restitucionConcurrentClasses)) {
  seedClasses('sierju_restitucion_tierras_2019', sectionCode, classes);
}

lines.push('');

const movements = JSON.parse(
  readFileSync(join(root, 'docs/sierju/movimientos-comunes.json'), 'utf8'),
) as {
  shared_first_instance_process: Array<{
    code: string;
    label: string;
    movement_kind: string;
    is_effective: boolean;
  }>;
  tutela_movimiento: Array<{
    code: string;
    label: string;
    movement_kind: string;
    is_effective: boolean;
  }>;
  desacato_movimiento: Array<{
    code: string;
    label: string;
    movement_kind: string;
    is_effective: boolean;
  }>;
  impugnacion_movimiento: Array<{
    code: string;
    label: string;
    movement_kind: string;
    is_effective: boolean;
  }>;
};

lines.push('-- Movement types (shared proceso 1a instancia)');
for (const m of movements.shared_first_instance_process) {
  lines.push(
    `insert into public.sierju_movement_types (section_id, code, label, movement_kind, is_effective, sort_order)`,
  );
  lines.push(
    `values (null, '${esc(m.code)}', '${esc(m.label)}', '${esc(m.movement_kind)}', ${m.is_effective}, ${movements.shared_first_instance_process.indexOf(m) + 1})`,
  );
  lines.push(
    `on conflict (section_id, code) do update set label = excluded.label, movement_kind = excluded.movement_kind, is_effective = excluded.is_effective, sort_order = excluded.sort_order;`,
  );
  lines.push('');
}

function seedSectionMovements(
  sectionForm: string,
  sectionCode: string,
  items: typeof movements.tutela_movimiento,
) {
  lines.push(`-- Movement types (${sectionCode})`);
  items.forEach((m, i) => {
    lines.push(
      `insert into public.sierju_movement_types (section_id, code, label, movement_kind, is_effective, sort_order)`,
    );
    lines.push(
      `select s.id, '${esc(m.code)}', '${esc(m.label)}', '${esc(m.movement_kind)}', ${m.is_effective}, ${i + 1}`,
    );
    lines.push(
      `from public.sierju_sections s where s.form_template_code = '${esc(sectionForm)}' and s.code = '${esc(sectionCode)}'`,
    );
    lines.push(
      `on conflict (section_id, code) do update set label = excluded.label, movement_kind = excluded.movement_kind, is_effective = excluded.is_effective, sort_order = excluded.sort_order;`,
    );
    lines.push('');
  });
}

seedSectionMovements('sierju_civil_circuito_2023_v4', 'movimiento_tutelas', movements.tutela_movimiento);
seedSectionMovements('sierju_civil_circuito_2023_v4', 'incidentes_desacato', movements.desacato_movimiento);
seedSectionMovements('sierju_civil_circuito_2023_v4', 'impugnaciones', movements.impugnacion_movimiento);

const outPath = join(root, 'supabase/seed/sierju_catalog_seed.sql');
writeFileSync(outPath, lines.join('\n'), 'utf8');
console.error(`Wrote ${outPath} (${lines.length} lines)`);
